services:
  # 1. Veritabanı Servisi
  db:
    image: postgres:15
    container_name: person_db_container
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: person_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # 2. Backend Servisi
  backend:
    build: ./backend
    container_name: person_backend_container
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user123
      DB_PASSWORD: password123
      DB_NAME: person_db
    depends_on:
      - db

  # 3. Frontend Servisi
  frontend:
    build: ./frontend
    container_name: person_frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend